apiVersion: v1
kind: Service
metadata:
 name: spring-boot-hello-world
 namespace: hw
spec:
 type: LoadBalancer
 selector:
   app: spring-boot-hello-world
 ports:
   - protocol: TCP
     port: 8081
     targetPort: 8081