apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-hello-world
  namespace: hw
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-hello-world
  template:
    metadata:
      labels:
        app: spring-boot-hello-world
    spec:
      containers:
        - name: spring-boot-hello-world
          image: hw:v3
          imagePullPolicy: Never
          ports:
            - containerPort: 8888